2019-02-16 18:46:27,659 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:49]
2019-02-16 18:51:48,489 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:49]
2019-02-16 18:51:56,456 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:49]
2019-02-16 19:27:58,940 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 19:28:24,288 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 19:34:43,237 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 19:34:51,372 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 23:01:19,492 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 23:04:30,860 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 23:04:39,226 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 23:04:44,756 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 23:06:13,230 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 23:08:13,802 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 23:08:22,264 ERROR: Exception on / [GET] [in c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\lenovo\microblog\app\routes.py", line 20, in before_request
    g.locale = str(get_locale())
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\lenovo\microblog\app\__init__.py", line 55, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'request' is not defined
2019-02-16 23:12:57,854 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 23:13:07,551 ERROR: Exception on / [GET] [in c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\lenovo\microblog\app\routes.py", line 20, in before_request
    g.locale = str(get_locale())
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\lenovo\microblog\app\__init__.py", line 55, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'request' is not defined
2019-02-16 23:16:01,353 ERROR: Exception on / [GET] [in c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\lenovo\microblog\app\routes.py", line 20, in before_request
    g.locale = str(get_locale())
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\lenovo\microblog\app\__init__.py", line 55, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'request' is not defined
2019-02-16 23:16:02,594 ERROR: Exception on / [GET] [in c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\lenovo\microblog\app\routes.py", line 20, in before_request
    g.locale = str(get_locale())
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\lenovo\microblog\app\__init__.py", line 55, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'request' is not defined
2019-02-16 23:16:11,663 INFO: Microblog startup [in C:\Users\lenovo\microblog\app\__init__.py:51]
2019-02-16 23:16:14,774 ERROR: Exception on / [GET] [in c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\lenovo\microblog\app\routes.py", line 20, in before_request
    g.locale = str(get_locale())
  File "c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\lenovo\microblog\app\__init__.py", line 55, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'request' is not defined
